user_input1 = int(input("Введите первое число: ")) 
user_input2 = int(input("Введите второе число: ")) 
user_input3 = int(input("Введите третье число: "))
user_input4 = int(input("Введите четвертое число: "))
print(f"{user_input4}{user_input3}{user_input2}{user_input1}")